# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
#
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set Up terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Verify Terraform repo downloaded 
        run: |
          mkdir /home/runner/work/nextjs-eks-tf/nextjs-eks-tf/bbuy-infra
          terraform version
          
      - name: Checkout Terraform code
        uses: actions/checkout@v3
        with:
            repository: hera1002/reac-test-app
            token: ${{secrets.PAT}}
            path: /home/runner/work/nextjs-eks-tf/nextjs-eks-tf/bbuy-infra
            
            



      - name: Step 2 with Dynamic Environment Variable
        run: |
          # Execute some commands or scripts to determine the variable value
          DYNAMIC_VALUE=$(terraform version)
          echo "DYNAMIC_VALUE=$DYNAMIC_VALUE" >> $GITHUB_ENV
          
      - name: Verify downloaded 
        run: |
          ls  /home/runner/work/nextjs-eks-tf/nextjs-eks-tf/bbuy-infra/
          cd  /home/runner/work/nextjs-eks-tf/nextjs-eks-tf/bbuy-infra/
          ls
          cd deployment-ecs/
          
          
